import type {
  User,
  DeliveryRequest,
  ChatMessage,
  ChatRoom,
} from "./types";

export const mockUser: User = {
  id: "u1",
  name: "Arjun Mehta",
  email: "arjun@college.edu",
  role: "hosteller",
  trustScore: 92,
  deliveries: 47,
  rating: 4.8,
  earnings: 2340,
};

export const mockDayScholar: User = {
  id: "u2",
  name: "Priya Sharma",
  email: "priya@college.edu",
  role: "dayscholar",
  trustScore: 88,
  deliveries: 63,
  rating: 4.9,
  earnings: 4120,
};

export const mockRequests: DeliveryRequest[] = [
  {
    id: "r1",
    itemName: "Maggi Noodles (Pack of 4)",
    quantity: 1,
    estimatedPrice: 56,
    urgency: "high",
    notes: "Any flavor is fine",
    status: "pending",
    hostelBlock: "Block A",
    createdBy: mockUser,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    reward: 20,
  },
  {
    id: "r2",
    itemName: "Notebook - A4 Ruled",
    quantity: 2,
    estimatedPrice: 120,
    urgency: "medium",
    notes: "200 pages preferred",
    status: "in_progress",
    hostelBlock: "Block C",
    createdBy: { ...mockUser, id: "u3", name: "Rohan Verma" },
    acceptedBy: mockDayScholar,
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    reward: 30,
  },
  {
    id: "r3",
    itemName: "Phone Charger (Type-C)",
    quantity: 1,
    estimatedPrice: 350,
    urgency: "high",
    notes: "Fast charging support needed",
    status: "buying",
    hostelBlock: "Block B",
    createdBy: { ...mockUser, id: "u4", name: "Sneha Reddy" },
    acceptedBy: mockDayScholar,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    reward: 50,
  },
  {
    id: "r4",
    itemName: "Cold Coffee (Large)",
    quantity: 2,
    estimatedPrice: 90,
    urgency: "low",
    status: "on_the_way",
    hostelBlock: "Block D",
    createdBy: { ...mockUser, id: "u5", name: "Karthik Nair" },
    acceptedBy: mockDayScholar,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    reward: 25,
  },
  {
    id: "r5",
    itemName: "Paracetamol Tablets",
    quantity: 1,
    estimatedPrice: 30,
    urgency: "high",
    notes: "Urgent, not feeling well",
    status: "delivered",
    hostelBlock: "Block A",
    createdBy: mockUser,
    acceptedBy: mockDayScholar,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    reward: 15,
  },
];

export const mockChatRoom: ChatRoom = {
  id: "chat1",
  requestId: "r2",
  participants: ["u1", "u2"],
  itemName: "Notebook - A4 Ruled",
  status: "in_progress",
};

export const mockMessages: ChatMessage[] = [
  {
    id: "m1",
    roomId: "chat1",
    senderId: "u2",
    type: "system",
    content: "Priya accepted your delivery request",
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "m2",
    roomId: "chat1",
    senderId: "u2",
    type: "text",
    content: "Hi! I'm heading to the stationery store now. Any brand preference?",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "m3",
    roomId: "chat1",
    senderId: "u1",
    type: "text",
    content: "Classmate or Navneet would be great. Thanks!",
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
  },
  {
    id: "m4",
    roomId: "chat1",
    senderId: "u2",
    type: "text",
    content: "Found Classmate notebooks. They have single line and four line. Which one?",
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: "m5",
    roomId: "chat1",
    senderId: "u1",
    type: "text",
    content: "Single line please!",
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
  },
  {
    id: "m6",
    roomId: "chat1",
    senderId: "u2",
    type: "price_confirmation",
    content: "Price confirmation for 2x Classmate Notebook",
    price: 130,
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "m7",
    roomId: "chat1",
    senderId: "u2",
    type: "image",
    content: "Here's what I got",
    imageUrl: "/placeholder-notebook.jpg",
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
];

export const itemSuggestions = [
  "Maggi Noodles",
  "Notebook",
  "Pen Set",
  "Phone Charger",
  "Cold Coffee",
  "Paracetamol",
  "Biscuits",
  "Water Bottle",
  "Chips",
  "Instant Coffee",
  "USB Cable",
  "Eraser",
  "Highlighters",
  "Face Wash",
  "Toothpaste",
];

export const quickReplies = [
  "On my way!",
  "Got it, thanks!",
  "How much time?",
  "Can you share location?",
  "Item not available",
  "Found an alternative",
];
